/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CreateImAccountOptions, CreateImRouteRuleOptions, ImAccountId, ImAccountMetadata, ImGuiCancelPendingAiOutboundOptions, ImGuiCreateSimulationInstanceOptions, ImGuiHistoryQueryOptions, ImGuiInboundView, ImGuiInjectMemberMessageOptions, ImGuiListOutboundOptions, ImGuiOutboundView, ImGuiRegisterManualOutboundOptions, ImRouteRule, ImRouteRuleId, ImSimulationInstance, ImSimulationInstanceId, ImWorkspaceSimulationConfig, SetWorkspaceSimulationTargetOptions, UpdateImRouteRuleOptions } from '@deepseek-ai/dsh-im-core/client'
import type { WorkspaceId } from '@deepseek-ai/dsh-workspace/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$696d436f6e666967 {
    createRouteRule: (options: CreateImRouteRuleOptions) => Promise<RemoteResult<ImRouteRule>>
    deleteAccount: (id: ImAccountId) => Promise<RemoteResult<boolean>>
    deleteRouteRule: (id: ImRouteRuleId) => Promise<RemoteResult<boolean>>
    deleteSimulationConfig: (workspaceId: WorkspaceId) => Promise<RemoteResult<boolean>>
    getSimulationConfig: (workspaceId: WorkspaceId) => Promise<RemoteResult<ImWorkspaceSimulationConfig | undefined>>
    listAccounts: () => Promise<RemoteResult<ImAccountMetadata[]>>
    listRouteRules: () => Promise<RemoteResult<ImRouteRule[]>>
    listSimulationConfigs: () => Promise<RemoteResult<ImWorkspaceSimulationConfig[]>>
    pauseAccount: (id: ImAccountId, paused: boolean) => Promise<RemoteResult<ImAccountMetadata>>
    setSimulationConfig: (options: SetWorkspaceSimulationTargetOptions) => Promise<RemoteResult<ImWorkspaceSimulationConfig>>
    updateRouteRule: (id: ImRouteRuleId, updates: UpdateImRouteRuleOptions) => Promise<RemoteResult<ImRouteRule>>
    upsertAccount: (options: CreateImAccountOptions) => Promise<RemoteResult<ImAccountMetadata>>
  }
  interface TypertRemoteNamespace$696d44656c6976657279 {
    cancelPendingAiOutbound: (options: ImGuiCancelPendingAiOutboundOptions) => Promise<RemoteResult<ImGuiOutboundView[]>>
    listOutbound: (options: ImGuiListOutboundOptions) => Promise<RemoteResult<ImGuiOutboundView[]>>
    queryHistory: (options: ImGuiHistoryQueryOptions) => Promise<RemoteResult<ImGuiInboundView[]>>
    registerManualOutbound: (options: ImGuiRegisterManualOutboundOptions) => Promise<RemoteResult<ImGuiOutboundView>>
  }
  interface TypertRemoteNamespace$696d53696d756c6174696f6e {
    createInstance: (options: ImGuiCreateSimulationInstanceOptions) => Promise<RemoteResult<ImSimulationInstance>>
    injectMemberMessage: (options: ImGuiInjectMemberMessageOptions) => Promise<RemoteResult<ImGuiInboundView>>
    listInstances: () => Promise<RemoteResult<ImSimulationInstance[]>>
    stopInstance: (instanceId: ImSimulationInstanceId) => Promise<RemoteResult<ImSimulationInstance>>
  }
  interface TypertRemoteMap {
    'imConfig/createRouteRule': (options: CreateImRouteRuleOptions) => Promise<RemoteResult<ImRouteRule>>
    'imConfig/deleteAccount': (id: ImAccountId) => Promise<RemoteResult<boolean>>
    'imConfig/deleteRouteRule': (id: ImRouteRuleId) => Promise<RemoteResult<boolean>>
    'imConfig/deleteSimulationConfig': (workspaceId: WorkspaceId) => Promise<RemoteResult<boolean>>
    'imConfig/getSimulationConfig': (workspaceId: WorkspaceId) => Promise<RemoteResult<ImWorkspaceSimulationConfig | undefined>>
    'imConfig/listAccounts': () => Promise<RemoteResult<ImAccountMetadata[]>>
    'imConfig/listRouteRules': () => Promise<RemoteResult<ImRouteRule[]>>
    'imConfig/listSimulationConfigs': () => Promise<RemoteResult<ImWorkspaceSimulationConfig[]>>
    'imConfig/pauseAccount': (id: ImAccountId, paused: boolean) => Promise<RemoteResult<ImAccountMetadata>>
    'imConfig/setSimulationConfig': (options: SetWorkspaceSimulationTargetOptions) => Promise<RemoteResult<ImWorkspaceSimulationConfig>>
    'imConfig/updateRouteRule': (id: ImRouteRuleId, updates: UpdateImRouteRuleOptions) => Promise<RemoteResult<ImRouteRule>>
    'imConfig/upsertAccount': (options: CreateImAccountOptions) => Promise<RemoteResult<ImAccountMetadata>>
    'imDelivery/cancelPendingAiOutbound': (options: ImGuiCancelPendingAiOutboundOptions) => Promise<RemoteResult<ImGuiOutboundView[]>>
    'imDelivery/listOutbound': (options: ImGuiListOutboundOptions) => Promise<RemoteResult<ImGuiOutboundView[]>>
    'imDelivery/queryHistory': (options: ImGuiHistoryQueryOptions) => Promise<RemoteResult<ImGuiInboundView[]>>
    'imDelivery/registerManualOutbound': (options: ImGuiRegisterManualOutboundOptions) => Promise<RemoteResult<ImGuiOutboundView>>
    'imSimulation/createInstance': (options: ImGuiCreateSimulationInstanceOptions) => Promise<RemoteResult<ImSimulationInstance>>
    'imSimulation/injectMemberMessage': (options: ImGuiInjectMemberMessageOptions) => Promise<RemoteResult<ImGuiInboundView>>
    'imSimulation/listInstances': () => Promise<RemoteResult<ImSimulationInstance[]>>
    'imSimulation/stopInstance': (instanceId: ImSimulationInstanceId) => Promise<RemoteResult<ImSimulationInstance>>
  }
  interface TypertRemoteNamespaceMap {
    'imConfig': TypertRemoteNamespace$696d436f6e666967
    'imDelivery': TypertRemoteNamespace$696d44656c6976657279
    'imSimulation': TypertRemoteNamespace$696d53696d756c6174696f6e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
