/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CreateImAccountOptions, CreateImRouteRuleOptions, ImAccountId, ImAccountMetadata, ImRouteRule, ImRouteRuleId, ImWorkspaceSimulationConfig, SetWorkspaceSimulationTargetOptions, UpdateImRouteRuleOptions } from '@deepseek-ai/dsh-im-core/client'
import type { WorkspaceId } from '@deepseek-ai/dsh-workspace/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$696d436f6e666967 {
    createRouteRule: (options: CreateImRouteRuleOptions) => Promise<RemoteResult<ImRouteRule>>
    deleteAccount: (id: ImAccountId) => Promise<RemoteResult<boolean>>
    deleteRouteRule: (id: ImRouteRuleId) => Promise<RemoteResult<boolean>>
    deleteSimulationConfig: (workspaceId: WorkspaceId) => Promise<RemoteResult<boolean>>
    getSimulationConfig: (workspaceId: WorkspaceId) => Promise<RemoteResult<ImWorkspaceSimulationConfig | undefined>>
    listAccounts: () => Promise<RemoteResult<ImAccountMetadata[]>>
    listRouteRules: (workspaceId?: WorkspaceId) => Promise<RemoteResult<ImRouteRule[]>>
    listSimulationConfigs: () => Promise<RemoteResult<ImWorkspaceSimulationConfig[]>>
    pauseAccount: (id: ImAccountId, paused: boolean) => Promise<RemoteResult<ImAccountMetadata>>
    setSimulationConfig: (options: SetWorkspaceSimulationTargetOptions) => Promise<RemoteResult<ImWorkspaceSimulationConfig>>
    updateRouteRule: (id: ImRouteRuleId, updates: UpdateImRouteRuleOptions) => Promise<RemoteResult<ImRouteRule>>
    upsertAccount: (options: CreateImAccountOptions) => Promise<RemoteResult<ImAccountMetadata>>
  }
  interface TypertRemoteMap {
    'imConfig/createRouteRule': (options: CreateImRouteRuleOptions) => Promise<RemoteResult<ImRouteRule>>
    'imConfig/deleteAccount': (id: ImAccountId) => Promise<RemoteResult<boolean>>
    'imConfig/deleteRouteRule': (id: ImRouteRuleId) => Promise<RemoteResult<boolean>>
    'imConfig/deleteSimulationConfig': (workspaceId: WorkspaceId) => Promise<RemoteResult<boolean>>
    'imConfig/getSimulationConfig': (workspaceId: WorkspaceId) => Promise<RemoteResult<ImWorkspaceSimulationConfig | undefined>>
    'imConfig/listAccounts': () => Promise<RemoteResult<ImAccountMetadata[]>>
    'imConfig/listRouteRules': (workspaceId?: WorkspaceId) => Promise<RemoteResult<ImRouteRule[]>>
    'imConfig/listSimulationConfigs': () => Promise<RemoteResult<ImWorkspaceSimulationConfig[]>>
    'imConfig/pauseAccount': (id: ImAccountId, paused: boolean) => Promise<RemoteResult<ImAccountMetadata>>
    'imConfig/setSimulationConfig': (options: SetWorkspaceSimulationTargetOptions) => Promise<RemoteResult<ImWorkspaceSimulationConfig>>
    'imConfig/updateRouteRule': (id: ImRouteRuleId, updates: UpdateImRouteRuleOptions) => Promise<RemoteResult<ImRouteRule>>
    'imConfig/upsertAccount': (options: CreateImAccountOptions) => Promise<RemoteResult<ImAccountMetadata>>
  }
  interface TypertRemoteNamespaceMap {
    'imConfig': TypertRemoteNamespace$696d436f6e666967
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
