/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type {
  MemberQuestionReceiverSnapshot,
  MemberQuestionRemoteAdmitHumanTurnRequest,
  MemberQuestionRemoteAdmitHumanTurnResponse,
  MemberQuestionRemoteSettleRequest,
  MemberQuestionRemoteSettleResponse,
} from '@deepseek-ai/dsh-member-question-receiver/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d656d6265725175657374696f6e {
    admitHumanTurn: (
      request: MemberQuestionRemoteAdmitHumanTurnRequest,
    ) => Promise<RemoteResult<MemberQuestionRemoteAdmitHumanTurnResponse>>
    settle: (request: MemberQuestionRemoteSettleRequest) => Promise<RemoteResult<MemberQuestionRemoteSettleResponse>>
    snapshot: () => Promise<RemoteResult<MemberQuestionReceiverSnapshot>>
  }
  interface TypertRemoteMap {
    'memberQuestion/admitHumanTurn': (
      request: MemberQuestionRemoteAdmitHumanTurnRequest,
    ) => Promise<RemoteResult<MemberQuestionRemoteAdmitHumanTurnResponse>>
    'memberQuestion/settle': (
      request: MemberQuestionRemoteSettleRequest,
    ) => Promise<RemoteResult<MemberQuestionRemoteSettleResponse>>
    'memberQuestion/snapshot': () => Promise<RemoteResult<MemberQuestionReceiverSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'memberQuestion': TypertRemoteNamespace$6d656d6265725175657374696f6e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
